Playlist:
    type: entity
    table: playlist
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: false
        author:
            type: string
            length: 255
            fixed: false
            nullable: false
        album:
            type: string
            length: 255
            fixed: false
            nullable: false
        year:
            type: string
            length: 255
            fixed: false
            nullable: false
        description:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
