SearchBundle_search:
    pattern:   /
    defaults:  { _controller: AcmeSearchBundle:Search:search }

SearchBundle_ajax:
    pattern: /ajax
    defaults: { _controller: AcmeSearchBundle:Search:getAjaxResults}
    requirements:
        _method: GET