SearchBundle_tracks:
    pattern: /tracks/
    defaults: { _controller: AcmeSearchBundle:Tracks:index }

SearchBundle_artists:
    pattern: /artists/
    defaults: { _controller: AcmeSearchBundle:Artists:index }

SearchBundle_category:
    pattern:   /category/
    defaults:  { _controller: AcmeSearchBundle:Category:index }

SearchBundle_ajax:
    pattern: /ajax
    defaults: { _controller: AcmeSearchBundle:Search:getAjaxResults}
    requirements:
        _method: GET

SearchBundle_discs:
    pattern: /discs/
    defaults: { _controller: AcmeSearchBundle:Discs:index }

SearchBundle_tracks_view:
        pattern: /tracks/view/{dId}/{aId}/{title}
        defaults: { _controller: AcmeSearchBundle:Tracks:view }

SearchBundle_category_view:
                pattern: /category/view/{name}/{id}
                defaults: { _controller: AcmeSearchBundle:Category:view }

SearchBundle_disc_view:
                pattern: /disc/view/{name}/{id}/{artistId}
                defaults: { _controller: AcmeSearchBundle:Discs:view }

SearchBundle_artist_view:
                pattern: /artists/view/{name}/{id}
                defaults: { _controller: AcmeSearchBundle:Artists:view }