SearchBundle_artists:
    pattern: /artists/page/{num}
    defaults: { _controller: AcmeSearchBundle:Artists:index }

SearchBundle_genres:
    pattern:   /category/page/{num}
    defaults:  { _controller: AcmeSearchBundle:Category:index }

SearchBundle_search:
    pattern:   /
    defaults:  { _controller: AcmeSearchBundle:Search:search }

SearchBundle_ajax:
    pattern: /ajax
    defaults: { _controller: AcmeSearchBundle:Search:getAjaxResults}
    requirements:
        _method: GET