SearchBundle_tracks:
    pattern: /tracks/
    defaults: { _controller: AcmeSearchBundle:Tracks:index }

SearchBundle_artists:
    pattern: /artists/
    defaults: { _controller: AcmeSearchBundle:Artists:index }

SearchBundle_category:
    pattern:   /category/
    defaults:  { _controller: AcmeSearchBundle:Category:index }

SearchBundle_search:
    pattern:   /
    defaults:  { _controller: AcmeSearchBundle:Search:search }

SearchBundle_ajax:
    pattern: /ajax
    defaults: { _controller: AcmeSearchBundle:Search:getAjaxResults}
    requirements:
        _method: GET